import { getPathname } from "./analyze.js";

// ─── REPORT TEXT ───

function generateReportText(conflicts) {
  let r = "";
  r += "=================================================\n";
  r += "  CANNISCOPE — Duplicate URL Targets Report\n";
  r += "=================================================\n\n";

  const seo = conflicts.filter(c => !c.isTechnical);
  const tech = conflicts.filter(c => c.isTechnical);

  const high = seo.filter(c => c.risk === "HIGH").length;
  const medium = seo.filter(c => c.risk === "MEDIUM").length;
  const low = seo.filter(c => c.risk === "LOW").length;
  const totalURLs = new Set(conflicts.flatMap(c => c.pages.map(p => p.url))).size;

  r += `Summary:\n`;
  r += `  SEO duplicate clusters: ${seo.length}\n`;
  r += `  Technical duplicates: ${tech.length}\n`;
  r += `  URLs involved: ${totalURLs}\n`;
  r += `  HIGH: ${high} | MEDIUM: ${medium} | LOW: ${low}\n\n`;

  const buckets = [
    { label: "HIGH RISK — FIX FIRST", filter: c => !c.isTechnical && c.risk === "HIGH" },
    { label: "MEDIUM RISK — CHECK", filter: c => !c.isTechnical && c.risk === "MEDIUM" },
    { label: "LOW RISK — MONITOR", filter: c => !c.isTechnical && c.risk === "LOW" },
    { label: "TECHNICAL DUPLICATES", filter: c => c.isTechnical },
  ];

  buckets.forEach(sec => {
    const items = conflicts.filter(sec.filter);
    if (items.length === 0) return;
    r += `=== ${sec.label} ===\n\n`;
    items.forEach((c, idx) => {
      r += `#${idx + 1}: ${c.isQuery ? "[QUERY OVERLAP] " : ""}${c.label}\n`;
      r += `${c.sections.join(" + ")} · ${c.pageCount} URLs · ${c.totalClicks} clicks · ${c.totalImpressions.toLocaleString()} impr · Severity: ${c.score} · ${c.confidenceLabel || "—"}\n`;
      r += `Traffic split: ${c.splitPct}% (${c.splitStrength}) · Expected impact: ${c.impact}\n`;
      if (c.positionConflict) r += `!! RANK/TRAFFIC MISMATCH — lower-traffic URL ranks higher; review structure. Do not redirect blindly.\n`;
      r += `\n>> ACTION: [${c.actionType}] ${c.suggestedAction}\n`;
      if (c.winner) r += `   Primary:   ${getPathname(c.winner.url)}\n`;
      if (c.loser)  r += `   Secondary: ${getPathname(c.loser.url)}\n\n`;
      r += `Why flagged:\n`;
      c.reasons.forEach(reason => { r += `  • ${reason}\n`; });
      if (c.recLong) r += `\n${c.recLong}\n\n`; else r += `\n`;
      r += `Pages:\n`;
      c.pages.forEach((p) => {
        const path = getPathname(p.url);
        const mark = p.action === "KEEP" ? "★" : " ";
        r += `  ${mark} ${path}\n`;
        r += `     Clicks: ${p.clicks} | Impr: ${p.impressions.toLocaleString()} | CTR: ${p.ctr}% | Pos: ${p.position.toFixed(1)} | ${p.section}\n`;
        r += `     → ${p.action}\n`;
      });
      r += `\n- - - - - - - - - - - - - - - - - - - - - - - -\n\n`;
    });
  });

  r += "=================================================\n";
  r += "  Generated by CanniScope\n";
  r += "=================================================\n";
  return r;
}

// ─── CSV EXPORT ───

function generateCSV(conflicts) {
  const rows = [["Cluster","Type","Risk","Confidence","Score","Action","Suggested Action","Primary URL","Secondary URL","Traffic Split %","Strength","Expected Impact","Migration Flag","Sections","URLs in cluster","Total Clicks","Total Impressions","Why Flagged"]];
  conflicts.forEach(c => {
    const type = c.isTechnical ? "Technical" : c.isQuery ? "Query overlap" : c.isLikelyArchitecture ? "Architecture" : "Same-target URLs";
    rows.push([
      c.label, type, c.risk, c.confidence || "—", c.score,
      c.actionType, c.suggestedAction,
      c.winner ? c.winner.url : "—",
      c.loser ? c.loser.url : "—",
      c.splitPct, c.splitStrength, c.impact,
      c.positionConflict ? "RANK/TRAFFIC MISMATCH" : "",
      c.sections.join(" + "), c.pageCount, c.totalClicks, c.totalImpressions,
      c.reasons.join("; "),
    ]);
  });
  return rows.map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n");
}

export { generateReportText, generateCSV };
